
import java.awt.BorderLayout;
import java.awt.List;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Bartu
 */
public class FilmWeb extends javax.swing.JFrame {

    /**
     * Creates new form FilmWeb
     */
    public FilmWeb() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        kullanıcı = new javax.swing.JButton();
        filmAraması = new javax.swing.JTextField();
        film_ara = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        vote_comment = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        kullanıcı.setText("Kullanıcı");
        kullanıcı.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullanıcıActionPerformed(evt);
            }
        });

        filmAraması.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filmAramasıActionPerformed(evt);
            }
        });

        film_ara.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        film_ara.setForeground(new java.awt.Color(255, 153, 0));
        film_ara.setText("Film Ara");
        film_ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                film_araActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Film Cenneti");

        vote_comment.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        vote_comment.setText("Vote and Comment");
        vote_comment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vote_commentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(kullanıcı, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(filmAraması, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(film_ara))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(vote_comment, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kullanıcı)
                .addGap(133, 133, 133)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filmAraması, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(film_ara, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(vote_comment, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kullanıcıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullanıcıActionPerformed
        AnaEkran anaEkran = new AnaEkran();
        anaEkran.setVisible(true);

    }//GEN-LAST:event_kullanıcıActionPerformed

    private void film_araActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_film_araActionPerformed
        
        String filmAdi = filmAraması.getText().trim();
        if (!filmAdi.isEmpty()) {
            try {
        String url = "jdbc:mysql://localhost:3306/imdb_movie_data";
        String username = "your_username"; // Kullanıcı adınız
        String password = "your_password"; // Parolanız

        Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/demo", DataBase.kullanici_adi, DataBase.parola);

        String query = "SELECT * FROM imdb_movie_data WHERE title LIKE ?";
        PreparedStatement preparedStatement = connection.prepareStatement(query);
        preparedStatement.setString(1, "%" + filmAdi + "%");
        ResultSet resultSet = preparedStatement.executeQuery();

        StringBuilder sb = new StringBuilder();
        while (resultSet.next()) {
            String title = resultSet.getString("title");
            String Genre = resultSet.getString("genre");
            int Year = resultSet.getInt("year");
            double Rating = resultSet.getDouble("Rating");

            sb.append("Title: ").append(title).append(" | Genre: ").append(Genre).append(" | Year: ").append(Year);
            sb.append("| Rating: ").append(Rating).append("\n");
        }

        JTextArea resultTextArea = new JTextArea();
        resultTextArea.setText(sb.toString());
        JOptionPane.showMessageDialog(this, new JScrollPane(resultTextArea));

        resultSet.close();
        preparedStatement.close();
        connection.close();
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Veritabanına bağlanırken veya sorgu yaparken hata oluştu!");
    }
        }   
         else {
            JOptionPane.showMessageDialog(this, "Lütfen film adını girin!");
        }
        
        // AnaEkran sınıfından loggedIn durumunu alalım (static değişkene erişelim)
    boolean loggedIn = AnaEkran.isLoggedIn();

    if (loggedIn) {
        // Film arama işlemini gerçekleştir
        JOptionPane.showMessageDialog(this, "Film arama işlemi başarılı !");
    } else {
        // Kullanıcı giriş yapmadığı için film arama işlemini engelle
        JOptionPane.showMessageDialog(this, "Film aramak için giriş yapmalısınız !");
    }
    }//GEN-LAST:event_film_araActionPerformed

    private void filmAramasıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filmAramasıActionPerformed
     

    }//GEN-LAST:event_filmAramasıActionPerformed

    private void vote_commentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vote_commentActionPerformed
        YorumEkleme yorum = new YorumEkleme();
        yorum.setVisible(true);
        
    }//GEN-LAST:event_vote_commentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilmWeb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilmWeb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilmWeb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilmWeb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FilmWeb().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField filmAraması;
    private javax.swing.JButton film_ara;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kullanıcı;
    private javax.swing.JButton vote_comment;
    // End of variables declaration//GEN-END:variables
}
